const stratagems = [
    {
        name: "Reinforce",
        department: "Mission Stratagems",
        type: "Common",
        arrows: "5",
        level: "0",
        cooldown: "120",
        calltime: "3.00",
        traits: ["Hellpod"],
        img: "images/common/Reinforce_Stratagem_Icon.webp"
    },
    {
        name: "MG-43 Machine Gun",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "1",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Support Weapon", "Hellpod", "Medium Armor Penetrating", "Stationary Reload"],
        img: "images/support/Machine_Gun_Stratagem_Icon.webp"
    },
    {
        name: "APW-1 Anti-Materiel Rifle",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "1",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Support Weapon", "Hellpod", "Heavy Armor Penetrating"],
        img: "images/support/Anti-Materiel_Rifle_Stratagem_Icon.webp"
    },
    {
        name: "M-105 Stalwart",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "6",
        level: "1",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Support Weapon", "Hellpod", "Light Armor Penetrating"],
        img: "images/support/Machine_Gun_Stratagem_Icon.webp"
    },
    {
        name: "EAT-17 Expendable Anti-Tank",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "3",
        cooldown: "70",
        calltime: "6.75",
        traits: ["Supply Weapon", "Hellpod", "Anti-Tank", "Expendable"],
        img: "images/support/Expendable_Anti-Tank_Stratagem_Icon.webp"
    },
    {
        name: "GR-8 Recoilless Rifle",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "5",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Supply Weapon", "Hellpod", "Backpack", "Anti-Tank", "Stationary Reload"],
        img: "images/support/Recoilless_Rifle_Stratagem_Icon.webp"
    },
    {
        name: "FLAM-40 Flamethrower",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "10",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Supply Weapon", "Hellpod", "Incendiary"],
        img: "images/support/Flamethrower_Stratagem_Icon.webp"
    },
    {
        name: "AC-8 Autocannon",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "6",
        level: "10",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Supply Weapon", "Hellpod", "Backpack", "Heavy Armor Penetrating", "Stationary Reload"],
        img: "images/support/Autocannon_Stratagem_Icon.webp"
    },
    {
        name: "MG-206 Heavy Machine Gun",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "12",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Supply Weapon", "Hellpod", "Heavy Armor Penetrating", "Stationary Reload"],
        img: "images/support/Heavy_Machine_Gun_Stratagem_Icon.webp"
    },
    {
        name: "RL-77 Airburst Rocket Launcher",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "15",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Supply Weapon", "Hellpod", "Backpack", "Medium Armor Penetrating", "Stationary Reload"],
        img: "images/support/RL-77_Airburst_Rocket_Launcher_Stratagem_Icon.webp"
    },
    {
        name: "MLS-4X Commando",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "15",
        cooldown: "120",
        calltime: "7.75",
        traits: ["Supply Weapon", "Hellpod", "Anti-Tank", "Expendable"],
        img: "images/support/Commando_Stratagem_Icon.webp"
    },
    {
        name: "RS-422 Railgun",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "6",
        level: "20",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Supply Weapon", "Hellpod", "Anti-Tank", "Chargeup"],
        img: "images/support/Railgun_Stratagem_Icon.webp"
    },
    {
        name: "FAF-14 Spear",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "20",
        cooldown: "480",
        calltime: "7.75",
        traits: ["Supply Weapon", "Hellpod", "Backpack", "Anti-Tank", "Stationary Reload"],
        img: "images/support/Spear_Stratagem_Icon.webp"
    },
    {
        name: "StA-X3 W.A.S.P. Launcher",
        department: "Patriotic Administration Center",
        type: "Supply",
        arrows: "5",
        level: "20",
        cooldown: "120",
        calltime: "7.75",
        traits: ["Supply Weapon", "Hellpod", "Backpack", "Anti-Tank", "Stationary Reload"],
        img: "images/support/Commando_Stratagem_Icon.webp"
    },
    {
        name: "Orbital Gatling Barrage",
        department: "Orbital Cannons",
        type: "Offensive",
        arrows: "5",
        level: "1",
        cooldown: "70",
        calltime: "3.05",
        traits: ["Explosive", "Orbital", "Heavy Armor Penetrating"],
        img: "images/offense/Orbital_Gatling_Barrage_Stratagem_Icon.png"
    },
    {
        name: "Orbital Airburst Strike",
        department: "Orbital Cannons",
        type: "Offensive",
        arrows: "3",
        level: "5",
        cooldown: "100",
        calltime: "4.45",
        traits: ["Explosive", "Orbital", "Medium Armor Penetrating"],
        img: "images/offense/Orbital_Airburst_Strike_Stratagem_Icon.webp"
    },
    {
        name: "Orbital 120mm HE Barrage",
        department: "Orbital Cannons",
        type: "Offensive",
        arrows: "6",
        level: "5",
        cooldown: "180",
        calltime: "7.45",
        traits: ["Explosive", "Orbital", "Anti-Tank"],
        img: "images/offense/Orbital_120mm_HE_Barrage_Stratagem_Icon.webp"
    },
    {
        name: "Orbital 380mm HE Barrage",
        department: "Orbital Cannons",
        type: "Offensive",
        arrows: "7",
        level: "8",
        cooldown: "240",
        calltime: "8.45",
        traits: ["Explosive", "Orbital", "Anti-Tank"],
        img: "images/offense/Orbital_380mm_HE_Barrage_Stratagem_Icon.webp"
    },
    {
        name: "Orbital Walking Barrage",
        department: "Orbital Cannons",
        type: "Offensive",
        arrows: "6",
        level: "10",
        cooldown: "240",
        calltime: "5.45",
        traits: ["Explosive", "Orbital", "Anti-Tank"],
        img: "images/offense/Orbital_Walking_Barrage_Stratagem_Icon.webp"
    },
    {
        name: "Orbital Laser",
        department: "Orbital Cannons",
        type: "Offensive",
        arrows: "5",
        level: "15",
        cooldown: "300",
        calltime: "2.00",
        traits: ["Orbital", "Anti-Tank", "Beam"],
        img: "images/offense/Orbital_Laser_Stratagem_Icon.webp"
    },
    {
        name: "Orbital Napalm Barrage",
        department: "Orbital Cannons",
        type: "Offensive",
        arrows: "6",
        level: "18",
        cooldown: "240",
        calltime: "7.45",
        traits: ["Explosive", "Orbital", "Incendiary"],
        img: "images/offense/Orbital_Napalm_Barrage_Stratagem_Icon.webp"
    },
    {
        name: "Orbital Railcannon Strike",
        department: "Orbital Cannons",
        type: "Offensive",
        arrows: "5",
        level: "20",
        cooldown: "210",
        calltime: "1.00",
        traits: ["Orbital", "Anti-Tank"],
        img: "images/offense/Orbital_Railcannon_Strike_Stratagem_Icon.webp"
    },
    {
        name: "Eagle Strafing Run",
        department: "Hangar",
        type: "Offensive",
        arrows: "3",
        level: "1",
        cooldown: "150",
        calltime: "2.40",
        traits: ["Eagle", "Heavy Armor Penetrating"],
        img: "images/offense/Eagle_Strafing_Run_Stratagem_Icon.webp"
    },
    {
        name: "Eagle Airstrike",
        department: "Hangar",
        type: "Offensive",
        arrows: "4",
        level: "1",
        cooldown: "150",
        calltime: "4.10",
        traits: ["Explosive", "Eagle", "Anti-Tank"],
        img: "images/offense/Eagle_Airstrike_Stratagem_Icon.webp"
    },
    {
        name: "Eagle Cluster Bomb",
        department: "Hangar",
        type: "Offensive",
        arrows: "5",
        level: "3",
        cooldown: "150",
        calltime: "4.10",
        traits: ["Explosive", "Eagle", "Medium Armor Penetrating"],
        img: "images/offense/Eagle_Cluster_Bomb_Stratagem_Icon.webp"
    },
    {
        name: "Eagle Napalm Airstrike",
        department: "Hangar",
        type: "Offensive",
        arrows: "4",
        level: "5",
        cooldown: "150",
        calltime: "4.10",
        traits: ["Explosive", "Eagle", "Incendiary"],
        img: "images/offense/Eagle_Napalm_Airstrike_Stratagem_Icon.webp"
    },
    {
        name: "LIFT-850 Jump Pack",
        department: "Hangar",
        type: "Supply",
        arrows: "5",
        level: "8",
        cooldown: "480",
        calltime: "9.75",
        traits: ["Hellpod", "Backpack"],
        img: "images/support/Jump_Pack_Stratagem_Icon.webp"
    },
    {
        name: "Eagle Smoke Strike",
        department: "Hangar",
        type: "Offensive",
        arrows: "4",
        level: "8",
        cooldown: "150",
        calltime: "4.40",
        traits: ["Explosive", "Eagle"],
        img: "images/offense/Eagle_Smoke_Strike_Stratagem_Icon.webp"
    },
    {
        name: "Eagle 110mm Rocket Pods",
        department: "Hangar",
        type: "Offensive",
        arrows: "4",
        level: "10",
        cooldown: "150",
        calltime: "3.40",
        traits: ["Explosive", "Eagle", "Anti-Tank"],
        img: "images/offense/Eagle_110mm_Rocket_Pods_Stratagem_Icon.webp"
    },
    {
        name: "Eagle 500kg Bomb",
        department: "Hangar",
        type: "Offensive",
        arrows: "5",
        level: "15",
        cooldown: "150",
        calltime: "3.45",
        traits: ["Explosive", "Eagle", "Anti-Tank"],
        img: "images/offense/Eagle_500kg_Bomb_Stratagem_Icon.webp"
    },
    {
        name: "M-102 Fast Reconnaissance Vehicle",
        department: "Hangar",
        type: "Supply",
        arrows: "7",
        level: "25",
        cooldown: "480",
        calltime: "10.50",
        traits: ["Vehicle"],
        img: "images/support/M-102_Fast_Recon_Vehicle_Stratagem_Icon.webp"
    },
    {
        name: "Orbital Precision Strike",
        department: "Bridge",
        type: "Offensive",
        arrows: "3",
        level: "1",
        cooldown: "90",
        calltime: "4.45",
        traits: ["Explosive", "Orbital", "Anti-Tank"],
        img: "images/offense/Orbital_Precision_Strike_Stratagem_Icon.webp"
    },
    {
        name: "Orbital Gas Strike",
        department: "Bridge",
        type: "Offensive",
        arrows: "4",
        level: "1",
        cooldown: "75",
        calltime: "4.45",
        traits: ["Explosive", "Orbital", "Caustic"],
        img: "images/offense/Orbital_Gas_Strike_Stratagem_Icon.webp"
    },
    {
        name: "Orbital EMS Strike",
        department: "Bridge",
        type: "Offensive",
        arrows: "4",
        level: "5",
        cooldown: "75",
        calltime: "4.45",
        traits: ["Orbital"],
        img: "images/offense/Orbital_EMS_Strike_Stratagem_Icon.webp"
    },
    {
        name: "Orbital Smoke Strike",
        department: "Bridge",
        type: "Offensive",
        arrows: "4",
        level: "8",
        cooldown: "100",
        calltime: "4.45",
        traits: ["Explosive", "Orbital"],
        img: "images/offense/Orbital_Smoke_Strike_Stratagem_Icon.webp"
    },
    {
        name: "E/MG-101 HMG Emplacement",
        department: "Bridge",
        type: "Defensive",
        arrows: "6",
        level: "10",
        cooldown: "180",
        calltime: "7.75",
        traits: ["Hellpod", "Heavy Armor Penetrating"],
        img: "images/defense/HMG_Emplacement_Stratagem_Icon.webp"
    },
    {
        name: "FX-12 Shield Generator Relay",
        department: "Bridge",
        type: "Defensive",
        arrows: "6",
        level: "10",
        cooldown: "90",
        calltime: "7.75",
        traits: ["Hellpod"],
        img: "images/defense/Shield_Generator_Relay_Stratagem_Icon.webp"
    },
    {
        name: "A/ARC-3 Tesla Tower",
        department: "Bridge",
        type: "Defensive",
        arrows: "6",
        level: "15",
        cooldown: "120",
        calltime: "7.75",
        traits: ["Hellpod", "Sentry"],
        img: "images/defense/Tesla_Tower_Stratagem_Icon.webp"
    },
    {
        name: "E/GL-21 Grenadier Battlement",
        department: "Bridge",
        type: "Defensive",
        arrows: "5",
        level: "15",
        cooldown: "120",
        calltime: "7.75",
        traits: ["Hellpod", "Explosive", "Medium Armor Penetrating"],
        img: "images/defense/GL-21_Grenadier_Battlement_Stratagem_Icon.webp"
    },
    {
        name: "MD-6 Anti-Personnel Minefield",
        department: "Engineering Bay",
        type: "Defensive",
        arrows: "4",
        level: "1",
        cooldown: "120",
        calltime: "7.75",
        traits: ["Hellpod", "Explosive", "Medium Armor Penetrating"],
        img: "images/defense/Anti-Personnel_Minefield_Stratagem_Icon.webp"
    },
];