const imageUrls = [
    "../../../public/images/support/Machine_Gun_Stratagem_Icon.webp",
    "../../../public/images/support/Anti-Materiel_Rifle_Stratagem_Icon.webp",
    "../../../public/images/support/Stalwart_Stratagem_Icon.webp",
    "../../../public/images/support/Machine_Gun_Stratagem_Icon.webp",
    "../../../public/images/support/Expendable_Anti-Tank_Stratagem_Icon.webp",
    "../../../public/images/support/Recoilless_Rifle_Stratagem_Icon.webp",
    "../../../public/images/support/Flamethrower_Stratagem_Icon.webp",
    "../../../public/images/support/Autocannon_Stratagem_Icon.webp",
    "../../../public/images/support/Heavy_Machine_Gun_Stratagem_Icon.webp",
    "../../../public/images/support/RL-77_Airburst_Rocket_Launcher_Stratagem_Icon.webp",
    "../../../public/images/support/Commando_Stratagem_Icon.webp",
    "../../../public/images/support/Railgun_Stratagem_Icon.webp",
    "../../../public/images/support/Spear_Stratagem_Icon.webp",
    "../../../public/images/support/Commando_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_Gatling_Barrage_Stratagem_Icon.png",
    "../../../public/images/offense/Orbital_Airburst_Strike_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_120mm_HE_Barrage_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_380mm_HE_Barrage_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_Walking_Barrage_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_Laser_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_Napalm_Barrage_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_Railcannon_Strike_Stratagem_Icon.webp",
    "../../../public/images/offense/Eagle_Strafing_Run_Stratagem_Icon.webp",
    "../../../public/images/offense/Eagle_Airstrike_Stratagem_Icon.webp",
    "../../../public/images/offense/Eagle_Cluster_Bomb_Stratagem_Icon.webp",
    "../../../public/images/offense/Eagle_Napalm_Airstrike_Stratagem_Icon.webp",
    "../../../public/images/support/Jump_Pack_Stratagem_Icon.webp",
    "../../../public/images/offense/Eagle_Smoke_Strike_Stratagem_Icon.webp",
    "../../../public/images/offense/Eagle_110mm_Rocket_Pods_Stratagem_Icon.webp",
    "../../../public/images/offense/Eagle_500kg_Bomb_Stratagem_Icon.webp",
    "../../../public/images/support/M-102_Fast_Recon_Vehicle_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_Precision_Strike_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_Gas_Strike_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_EMS_Strike_Stratagem_Icon.webp",
    "../../../public/images/offense/Orbital_Smoke_Strike_Stratagem_Icon.webp",
    "../../../public/images/defense/HMG_Emplacement_Stratagem_Icon.webp",
    "../../../public/images/defense/Shield_Generator_Relay_Stratagem_Icon.webp",
    "../../../public/images/defense/Tesla_Tower_Stratagem_Icon.webp",
    "../../../public/images/defense/GL-21_Grenadier_Battlement_Stratagem_Icon.webp",
    "../../../public/images/defense/Anti-Personnel_Minefield_Stratagem_Icon.webp",
    "../../../public/images/support/Supply_Pack_Stratagem_Icon.webp",
    "../../../public/images/support/Grenade_Launcher_Stratagem_Icon.webp",
    "../../../public/images/support/Laser_Cannon_Stratagem_Icon.webp",
    "../../../public/images/defense/Incendiary_Mines_Stratagem_Icon.webp",
    "../../../public/images/support/Guard_Dog_Rover_Stratagem_Icon.webp",
    "../../../public/images/support/Ballistic_Shield_Backpack_Stratagem_Icon.webp",
    "../../../public/images/support/Arc_Thrower_Stratagem_Icon.webp",
    "../../../public/images/defense/MD-17_Anti-Tank_Mines_Stratagem_Icon.webp",
    "../../../public/images/support/Quasar_Cannon_Stratagem_Icon.webp",
    "../../../public/images/support/Shield_Generator_Pack_Stratagem_Icon.webp",
    "../../../public/images/defense/Gas_Minefield_Stratagem_Icon.webp",
    "../../../public/images/defense/Machine_Gun_Sentry_Stratagem_Icon.webp",
    "../../../public/images/defense/Gatling_Sentry_Stratagem_Icon.webp",
    "../../../public/images/defense/Mortar_Sentry_Stratagem_Icon.webp",
    "../../../public/images/support/Guard_Dog_Stratagem_Icon.webp",
    "../../../public/images/defense/Autocannon_Sentry_Stratagem_Icon.webp",
    "../../../public/images/defense/Rocket_Sentry_Stratagem_Icon.webp",
    "../../../public/images/defense/AM-23_EMS_Mortar_Sentry_Stratagem_Icon.webp",
    "../../../public/images/support/EXO-45_Patriot_Exosuit_Stratagem_Icon.webp",
    "../../../public/images/support/EXO-49_Emancipator_Exosuit_Stratagem_Icon.webp",
    "../../../public/images/support/Sterilizer_Stratagem_Icon.webp",
    "../../../public/images/support/Guard_Dog_Dog_Breath_Stratagem_Icon.webp",
    "../../../public/images/support/SH-51_Directional_Shield_Stratagem_Icon.webp",
    "../../../public/images/defense/E_AT-12_Anti-Tank_Emplacement_Stratagem_Icon.webp",
    "../../../public/images/defense/A_FLAM-40_Flame_Sentry_Stratagem_Icon.webp",
    "../../../public/images/support/Portable_Hellbomb_Stratagem_Icon.webp",
    "../../../public/images/support/Hover_Pack_Stratagem_Icon.webp",
    "../../../public/images/support/CQC-1_One_True_Flag_Stratagem_Icon.webp",
    "../../../public/images/support/GL-52_De-Escalator_Stratagem_Icon.webp",
    "../../../public/images/support/AX_ARC-3__Guard_Dog__K-9_Stratagem_Icon.webp",
    "../../../public/images/support/PLAS-45_Epoch_Stratagem_Icon.webp",
    "../../../public/images/defense/A_LAS-98_Laser_Sentry_Stratagem_Icon.webp",
    "../../../public/images/support/LIFT-182_Warp_Pack_Stratagem_Icon.webp",
    "../../../public/images/support/S-11_Speargun_Stratagem_Icon.webp",
    "../../../public/images/support/EAT-700_Expendable_Napalm_Stratagem_Icon.webp",
    "../../../public/images/support/MS-11_Stratagem_Icon.webp",
    "../../../public/images/common/Reinforce_Stratagem_Icon.webp",
    "../../../public/images/common/SOS_Beacon_Stratagem_Icon.webp",
    "../../../public/images/objective/Hellbomb_Stratagem_Icon.webp",
    "../../../public/images/objective/Dark_Fluid_Vessel_Stratagem_Icon.webp",
    "../../../public/images/icons/wing%20left.png",
    "../../../public/images/icons/wing%20right.png",
    "../../../public/images/icons/StarFilled.png",
    "../../../public/images/icons/StarEmpty.png",
    "../../../public/images/icons/req.PNG",
    "../../../public/images/icons/xp.PNG"
];

function preloadImage(url) {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.onload = resolve;
        img.onerror = reject;
        img.src = url;
    });
}

Promise.all(imageUrls.map(preloadImage))
    .then(() => console.log("All images preloaded"))
    .catch(err => console.error("Image failed to load:", err));
